name: build-latex
on:
  push:
    tags:
      - 'v*'

jobs:
  build-latex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: slides.tex
          latexmk_use_xelatex: true

      - name: Upload a PDF file to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: slides.pdf
          asset_name: slides.pdf
          tag: ${{ github.ref }}
          overwrite: true